language: python
python:
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
install:
- pip install pydiatra pyflakes
script:
- python3 -m pydiatra .
- python3 -m pyflakes .
- make install PREFIX=~/.local
- cd /
- exp509 -t 7 www.example.org
- exp509 -t 1100 www.example.org; [ $? -eq 1 ]

# vim:ts=2 sts=2 sw=2 et
