#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import datetime
import socket
import ssl
import sys
import time

...  # Python >= 3.4 is required

def require_python(*version):
    if sys.version_info < version:
        version_str = '.'.join(str(x) for x in version)
        message = 'Python >= {0} is required'.format(version_str)
        raise RuntimeError(message)

def main():
    require_python(3, 4)
    ap = argparse.ArgumentParser()
    ap.add_argument('-t', '--threshold', metavar='N', required=True,
        help='alert when cert expires in N days (or less)',
        type=int,
    )
    ap.add_argument('hosts', metavar='HOST[:PORT]', nargs='+')
    options = ap.parse_args()
    threshold = datetime.timedelta(days=options.threshold)
    context = ssl.create_default_context()
    rc = 0
    for host in options.hosts:
        orig_host = host
        if ':' in host:
            host, port = host.rsplit(':')
            port = int(port)
        else:
            port = 443
        tsock = context.wrap_socket(
            socket.socket(),
            server_hostname=host
        )
        try:
            tsock.connect((host, port))
            cert = tsock.getpeercert()
        finally:
            tsock.close()
        exp = cert['notAfter']
        exp = datetime.datetime.strptime(exp, '%b %d %H:%M:%S %Y GMT')
        exp = exp.replace(tzinfo=datetime.timezone.utc)
        now = datetime.datetime.now(datetime.timezone.utc)
        if (exp - now < threshold):
            lexp = time.localtime(exp.timestamp())
            lexp = time.strftime('%Y-%m-%d %H:%M', lexp)
            print('{host}: certificate expires on {exp}'.format(host=orig_host, exp=lexp))
            rc = 1
    sys.exit(rc)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
